name: Conda package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: "CI setup"

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.x"
          - "3.12"
          - "3.11"
          - "3.10"

        os:
          - "ubuntu-latest"

    runs-on: "${{ matrix.os }}"

    # use bash everywhere
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: DeepForest
          environment-file: environment.yml
          extra-specs: "python=${{ matrix.python-version }}"
          cache-env: true
          cache-downloads: true

      - name: Run pytest, test style, and notebooks
        run: |
          pytest -v
          yapf -d --recursive deepforest/ --style=.style.yapf
          pytest --nbmake docs/*.ipynb

      - name: Test Docs
        run: |
          cd docs && make clean && make html SPHINXOPTS="-W"
